SMPManager/
├── pom.xml
├── src/
│   └── main/java/com/smpmanager/SMPManager.java
│   └── main/resources/plugin.yml
└── .github/
    └── workflows/maven-build.yml
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
         http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.smpmanager</groupId>
    <artifactId>SMPManager</artifactId>
    <version>1.0.0</version>
    <packaging>jar</packaging>

    <name>SMPManager</name>

    <repositories>
        <repository>
            <id>spigot-repo</id>
            <url>https://hub.spigotmc.org/nexus/content/repositories/snapshots/</url>
        </repository>
    </repositories>

    <dependencies>
        <dependency>
            <groupId>org.bukkit</groupId>
            <artifactId>bukkit</artifactId>
            <version>1.21.8-R0.1-SNAPSHOT</version>
            <scope>provided</scope>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.10.1</version>
                <configuration>
                    <source>17</source>
                    <target>17</target>
                </configuration>
            </plugin>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-jar-plugin</artifactId>
                <version>3.3.0</version>
                <configuration>
                    <archive>
                        <manifest>
                            <addClasspath>true</addClasspath>
                            <mainClass>com.smpmanager.SMPManager</mainClass>
                        </manifest>
                    </archive>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>
package com.smpmanager;

import org.bukkit.plugin.java.JavaPlugin;

public class SMPManager extends JavaPlugin {
    @Override
    public void onEnable() {
        getLogger().info("SMPManager enabled!");
    }
    @Override
    public void onDisable() {
        getLogger().info("SMPManager disabled!");
    }
}
name: SMPManager
version: 1.0.0
main: com.smpmanager.SMPManager
api-version: 1.21
commands:
  coins:
    description: Check your coins
  pay:
    description: Pay coins to a player
  setcoins:
    description: Admin command to set coins
    permission: smp.setcoins
name: Build SMPManager
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with: {distribution: temurin, java-version: 17}
      - run: mvn clean package
      - uses: actions/upload-artifact@v3
        with: {name: SMPManager, path: target/SMPManager-1.0.0.jar}
